/vis/open OGL

# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/set/lightsVector -1 0 0

/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
/vis/viewer/set/upVector 0 0 1


/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories rich
/vis/modeling/trajectories/create/drawByParticleID
/vis/scene/endOfEventAction accumulate
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 1
/vis/modeling/trajectories/drawByParticleID-0/set e+ white
/vis/modeling/trajectories/drawByParticleID-0/set e- white
/vis/modeling/trajectories/drawByParticleID-0/set gamma yellow
/vis/modeling/trajectories/drawByParticleID-0/set neutron magenta
/vis/modeling/trajectories/drawByParticleID-0/set proton blue
/vis/modeling/trajectories/drawByParticleID-0/set pi+ red
/vis/modeling/trajectories/drawByParticleID-0/set pi- red
/vis/modeling/trajectories/drawByParticleID-0/set pi0 grey
/vis/modeling/trajectories/drawByParticleID-0/set mu- red
/vis/modeling/trajectories/drawByParticleID-0/set mu+ red
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton white

/vis/viewer/set/autoRefresh true
/vis/verbose warnings
/vis/viewer/refresh